### ISSUE TITLE
피드에서 토스트가 계속 보이는 버그

### ISSUE THREAD

**Issue by 2donny** [Xircle/4oclock-client#45]
<img width="359" alt="스크린샷 2021-10-01 오후 4 53 43" src="https://user-images.githubusercontent.com/58783348/135585098-d367da43-8b15-47e8-863d-d7582d3a3748.png">

디테일 페이지 갔다가 -> 뒤로가기 버튼 누르면(history.goBack()) -> query-parameter에 isLoggedIn이 남는다. -> toast가 뜬다

해결 방안) query-parameter에 조건을 추가하거나, 뒤로가기 버튼을 누를 때 window.replace를 써야할듯 
# 브라우저 뒤로가기 버튼은 어떻게해야하나?

**Comment by dja1716** [comment]
done
